// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigRequirements } from "./ConfigRequirements";

export type ConfigRequirementsReadResponse = {
/**
 * Whether Fast and Ultra Fast requirements are enforced independently.
 * Older servers omit this field and use Fast mode as a shared speed gate.
 */
supportsIndependentSpeedModes: boolean | null,
/**
 * Null if no requirements are configured (e.g. no requirements.toml/MDM entries).
 */
requirements: ConfigRequirements | null, };
