// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EnvironmentSkillsParams = {
/**
 * Exact catalog names that must be available from this environment.
 */
required?: Array<string> | null, };
